# Generated by Django 3.1.3 on 2020-12-11 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='user/avatars', verbose_name='avatar'),
        ),
    ]
