# Generated by Django 3.1.3 on 2020-12-11 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201212_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(unique=True, unique_for_date='publish_time', verbose_name='Slug'),
        ),
    ]
